### ISSUE TITLE
An unexpected exception occured: 'We are already refreshing the product url key's, just have a little patience

### ISSUE THREAD

**Issue by JoergLindner** [baldwin-agency/magento2-module-url-data-integrity-checker#24]
Hi we got an issue as we use ctrl+c by mistake while checker was running in CLI
How to clear that?
An unexpected exception occured: 'We are already refreshing the product url key's, just have a little patience 🙂'
#0 /var/www/vhosts/xxxx/httpdocs/vendor/baldwin/magento2-module-url-data-integrity-checker/Console/Command/CheckProductUrlKeys.php(69): Baldwin\UrlDataIntegrityChecker\Updater\Catalog\Product\UrlKey->refresh()
#1 /var/www/vhosts/xxxx/httpdocs/vendor/symfony/console/Command/Command.php(255): Baldwin\UrlDataIntegrityChecker\Console\Command\CheckProductUrlKeys->execute()
#2 /var/www/vhosts/xxxxx/httpdocs/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run()
#3 /var/www/vhosts/xxxx/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Baldwin\UrlDataIntegrityChecker\Console\Command\CheckProductUrlKeys\Interceptor->___callParent()
#4 /var/www/vhosts/xxxx/httpdocs/vendor/magento/framework/Interception/Interceptor.php(153): Baldwin\UrlDataIntegrityChecker\Console\Command\CheckProductUrlKeys\Interceptor->Magento\Framework\Interception\{closure}()
#5 /var/www/vhosts/xxxx/httpdocs/generated/code/Baldwin/UrlDataIntegrityChecker/Console/Command/CheckProductUrlKeys/Interceptor.php(23): Baldwin\UrlDataIntegrityChecker\Console\Command\CheckProductUrlKeys\Interceptor->___callPlugins()
#6 /var/www/vhosts/xxxxx/httpdocs/vendor/symfony/console/Application.php(1009): Baldwin\UrlDataIntegrityChecker\Console\Command\CheckProductUrlKeys\Interceptor->run()
#7 /var/www/vhosts/xxxxx/httpdocs/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#8 /var/www/vhosts/xxxxx/httpdocs/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun()
#9 /var/www/vhosts/xxxx/httpdocs/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#10 /var/www/vhosts/xxxxx/httpdocs/bin/magento(23): Symfony\Component\Console\Application->run()
#11 {main}

Seems that a task is stuck.

Regards
Joerg

**Comment by JoergLindner** [comment]
OK found it. need to run commond with -f to force it and clear that the process is running. Might be a good idea to make a Reset command too.
